repos:
  # Default pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # Ensure EOF exists
      - id: end-of-file-fixer
      # Prevent adding large files
      - id: check-added-large-files
        args: ["--maxkb=5000"]
  # Solidity pre-commit hooks
  - repo: local
    hooks:
      - id: lint
        name: Lint solidity files via forge fmt
        description: Lint solidity code via forge fmt
        language: system
        stages: [commit]
        entry: bash -c 'make format'
        pass_filenames: false
