[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.19"
optimizer_runs = 1000000
evm_version = "paris"
via_ir = true

[fmt]
number_underscore = "thousands"
single_line_statement_blocks = "multi"
